#!/bin/bash
##
## xkcd.sh

## Get a random xkcd cartoon and display it with feh
## by @damo <https://forums.bunsenlabs.org/viewtopic.php?pid=92679#p92679>

## One-liner:.com
#feh "$(wget -O - "https://c.xkcd.com/random/comic"  | grep "Image URL" | awk '{print $5}')"

URL="https://c.xkcd.com/random/comic"
PAGE="$(wget -O - $URL  | grep "Image URL" | awk '{print $5}')"
feh "$PAGE" &
exit 0
