#!/bin/bash
##
## xkcd.sh

## Get a random xkcd cartoon and display it with feh
## by @damo <Oct 2019>
## updated by MX Devs Dec 2022

## One-liner:
#feh "$(wget -O - "https://c.xkcd.com/random/comic"  | grep "Image URL" | awk '{print $5}')"

URL="https://c.xkcd.com/random/comic"
PAGELINK="$(wget -O - $URL  | grep "Image URL" | awk '{print $7}')"
PAGE=$(echo $PAGELINK | grep -o -P '(?<=>).*(?=</a>)')

feh $PAGE &
