#!/bin/bash
#Rofi-Manager
#Tool to manage rofi settings
#V.0.1 by Melber and MX Devs, 05 September 2022
#License: GPL-3.0+

#define some variables

TITLE="MX-Rofi-Manager"
CLASS="mxrm"
ROFIPATH="$HOME/.config/rofi/themes"
ICONPATH="/usr/share/pixmaps/mxrm-icon.png"
#HELPPATH="/usr/share/pixmaps/mxrm-help.png"


#delete stylelist and tempclr after use
#trap "rm -r "$ROFIPATH/tempdir" " EXIT

#
if [ ! -d $ROFIPATH ]; then

mkdir $ROFIPATH

fi

#create tempdir

if [ ! -d $ROFIPATH/tempdir ]; then

  mkdir -p $ROFIPATH/tempdir

fi



#################################
# function rofi_theme

rofi_theme() {

TITLE="Rofi-Theme"
CLASS="mxrm"
ROFIPATH="$HOME/.config/rofi/themes"
ROFIPATHUSR="/usr/share/rofi/themes"
ICONPATH="/usr/share/pixmaps/mxrm-icon.png"
#HELPPATH="/usr/share/pixmaps/mxrm-help.png"


#read available themes

cd $ROFIPATH
ls -f *rasi > $ROFIPATH/tempdir/rasilist.txt
cd $ROFIPATHUSR
ls -f *rasi >> $ROFIPATH/tempdir/rasilist.txt

sed -i 's|.rasi||g' $ROFIPATH/tempdir/rasilist.txt


#select theme

TEXTTHEME1="\n<b>Select rofi theme to make current</b>\n"

NEWTHEME=$( yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --text="$TEXTTHEME1" --width=600 --height=400 --borders=20 --center --list --no-headers --separator="" --column=Style --text-align=left < $ROFIPATH/tempdir/rasilist.txt )

GETOUT=$(echo "$?")

if [ "$GETOUT" != 0 ]; then

  exit

fi


#make current

cd $HOME/.config/rofi/

ROFIOLD="$(grep "themes" $HOME/.config/rofi/config.rasi)"
ROFIOLD=$(echo "${ROFIOLD}" | sed -e 's/[]$\/*[\^]/\\&/g' )


if [ ! -f $ROFIPATH/$NEWTHEME.rasi ]; then

ROFINEW="@import \""$ROFIPATHUSR"/"$NEWTHEME".rasi"\"
ROFINEW=$(echo "${ROFINEW}" | sed -e 's/[]$\/*[\^]/\\&/g' )

else

ROFINEW="@import \""$ROFIPATH"/"$NEWTHEME".rasi"\"
ROFINEW=$(echo "${ROFINEW}" | sed -e 's/[]$\/*[\^]/\\&/g' )

fi

cd $HOME/.config/rofi
sed -i -e "s/${ROFIOLD}/${ROFINEW}/g" config.rasi


TEXTTHEME2="All done!\n\n<b>"$NEWTHEME"</b> has been set as the current rofi theme.\n\n"

  yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=200 --fixed --center --borders=20 --text=$"$TEXTTHEME2" --text-align=center --button="OK" \

exit

}


#################################
# function rofi_tabs

rofi_tabs() {

TITLE="Rofi-Tab-Selector"
CLASS="mxrm"
ROFIPATH="$HOME/.config/rofi/themes"
ROFIPATHUSR="/usr/share/rofi/themes"
ICONPATH="/usr/share/pixmaps/mxrm-icon.png"
#HELPPATH="/usr/share/pixmaps/mxrm-help.png"

TEXTTABS1=$"\n<b>Select which tabs rofi should use</b>

drun: the MX-21 default that displays available apps
calc: a powerful calculation engine
help: a set of links about using rofi
none: tab will not be shown

"

TABS=(yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --text="$TEXTTABS1" --text-align=left --height=400 --width=600 --borders=20 --center --separator=" " --form --columns=3 --button="gtk-quit":1 --button="gtk-ok":0 \
--field="1st Tab":CB "drun!calc!help!" \
--field="2nd Tab":CB "help!calc!drun!none" \
--field="3rd Tab":CB "none!help!calc!drun" \
)

NEWTABS=$("${TABS[@]}")
(($?==0)) && echo "$NEWTABS" > $ROFIPATH/tempdir/temptabs.txt

GETOUT=$(echo "$?")

if [ "$GETOUT" != 0 ]; then

  exit

fi

read -r -a TEMPTABS < $ROFIPATH/tempdir/temptabs.txt

TAB0="${TEMPTABS[0]}"
TAB1="${TEMPTABS[1]}"
TAB2="${TEMPTABS[2]}"

NEWTABS="modi: \""$TAB0","$TAB1","$TAB2"\";"

NEWTABS=$(echo "${NEWTABS}" | sed -e "s/help/help\:\~\/.config\/rofi\/rofi-help/g" )
NEWTABS=$(echo "${NEWTABS}" | sed -e "s/calc/calc\:qalc/g" )
NEWTABS=$(echo "${NEWTABS}" | sed -e "s/,none//g" )

NEWTABS=$(echo "${NEWTABS}" | sed -e 's/[]$\/*[\^]/\\&/g' )


OLDTABS="$(grep "modi" $HOME/.config/rofi/config.rasi)"
OLDTABS=$(echo "${OLDTABS}" | sed -e 's/[]$\/*[\^]/\\&/g' )


cd $HOME/.config/rofi/
sed -i -e "s/${OLDTABS}/${NEWTABS}/g" config.rasi

TEXTTABS2=$"All done!\n\nTab configuration has been updated.\n\n"

  yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=200 --fixed --center --borders=20 --text="$TEXTTABS2" --text-align=center --button="OK" \


exit

}


#################################
# function rofi_edit

rofi_edit() {

TITLE="Rofi-Edit"
CLASS="mxrm"
ROFIPATH="$HOME/.config/rofi/themes"
ROFIPATHUSR="/usr/share/rofi/themes"
ICONPATH="/usr/share/pixmaps/mxrm-icon.png"
#HELPPATH="/usr/share/pixmaps/mxrm-help.png"


#read available themes

cd $ROFIPATH
ls -f *rasi > $ROFIPATH/tempdir/editlist.txt
cd $ROFIPATHUSR
ls -f *rasi >> $ROFIPATH/tempdir/editlist.txt


#select theme

TEXTEDIT1=$"\n<b>Select the rofi theme you wish to edit</b>

The .rasi file will be opened in geany\n\n"

EDITTHEME=$( yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --text="$TEXTEDIT1" --width=600 --height=400 --borders=20 --center --list --no-headers --separator="" --column=Style --text-align=left < $ROFIPATH/tempdir/editlist.txt )

GETOUT=$(echo "$?")

if [ "$GETOUT" != 0 ]; then

  exit

fi

if [ ! -f $ROFIPATH/$EDITTHEME ]; then

EDITTHEME="$ROFIPATHUSR/$EDITTHEME"

else

EDITTHEME="$ROFIPATH/$EDITTHEME"

fi

geany $EDITTHEME

exit

}

#################################

export -f rofi_theme rofi_tabs rofi_edit

#################################
#MAIN WINDOW


TITLE="MX-Rofi-Manager"
CLASS="mxrm"
ROFIPATH="$HOME/.config/rofi/themes"
ICONPATH="/usr/share/pixmaps/mxrr-icon.png"
#HELPPATH="/usr/share/pixmaps/mxrr-help.png"

TEXTMXRM="\nRofi Manager is a tool to amend rofi settings.\n\nWhat would you like to do?\n\n"

yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --borders=20 --center --width=600 --height=400 --fixed --form --text-align=center --text="$TEXTMXRM" --button="gtk-close" \
--field='- Change the current rofi theme -:BTN' 'bash -c rofi_theme' \
--field='- Change the configuration of the rofi tabs -:BTN' 'bash -c rofi_tabs' \
--field='- Recolor a rofi theme based on MX-comfort -:BTN' 'bash -c mxrr' \
--field='- Edit a rofi theme config file -:BTN' 'bash -c rofi_edit' \
