#! /bin/bash

### mxfb-appearance provides graphical access to the rootMenu entries Appearance and Settings > Fluxbox > Toolbar
## it was released November 2020 by MX Linux Devs under a GPLv3 license 

## conky-manager-mxfb.png and mx-dockmaker64.png were created by user ceeslans

TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN="mxfb-appearance"

TITLE=$"Fluxbox Appearance"
BUTTON0=$"Toolbar"
BUTTON1=$"Conky"
BUTTON2=$"Docks"
BUTTON3=$"Desktop icons"
BUTTON4=$"Style"
BUTTON5=$"Theme"
BUTTON6=$"Toolbar toggle"
BUTTON7=$"Wallpaper"



yad --geometry=200x64 --center --title=$TITLE \
--button="!/usr/share/icons/panel64.png!$BUTTON0":flux-toolbar \
--button="!/usr/share/icons/conky-manager-mxfb.png!$BUTTON1":conky-manager2 \
--button="!/usr/share/icons/mx-dockmaker64_nologo.png!$BUTTON2":mx-dockmaker \
--button="""!/usr/share/icons/Moka/64x64/apps/direct-connect.png!$BUTTON3":mx-idesktool \
--button="""!/usr/share/icons/Moka/64x64/apps/multisystem.png!$BUTTON4":choosefile \
--button="""!/usr/share/icons/Moka/64x64/apps/cs-themes.png!$BUTTON5":lxappearance \
--button="""!/usr/share/icons/Moka/64x64/apps/cs-general.png!$BUTTON6":toggletint2 \
--button="!/usr/share/icons/Moka/64x64/apps/background.png!$BUTTON7":nitrogen \
--window-icon=/usr/share/icons/mxflux.png






